const mysql = require('mysql');

let db = mysql.createConnection({
    host: "localhost",
    user: "root",
    password: '7{aH$mkLP@vfpW-!',
    database: 'equinox_cad'
});

const cars = [
    "Albany Alpha		",
    "Albany Buccaneer		",
    "Albany Buccaneer Custom		",
    "Albany Cavalcade		",
    "Albany Cavalcade FXT		",
    "Albany Emperor		",
    "Albany Esperanto		",
    "Albany Franken Stange		",
    "Albany Hermes		",
    "Albany Lurcher		",
    "Albany Manana		",
    "Albany Police Roadcruiser		",
    "Albany Presidente		",
    "Albany Primo		",
    "Albany Primo Custom		", , ,
    "Albany Taxi Cab		",
    "Albany Romero		", ,
    "Albany Roosevelt		",
    "Albany Roosevelt Valor		",
    "Albany Stretch		", ,
    "Albany Virgo		",
    "Albany Washington		", ,
    "Annis Elergy Retro Custom		",
    "Annis Elergy RH8		",
    "Annis RE7B		",
    "Annis Savestra		",
    "Benefactor Dubsta		",
    "Benefactor Dubsta 6X6		",
    "Benefactor Feltzer		",
    "Benefactor Glendale		",
    "Benefactor Panto		",
    "Benefactor Schafter		",
    "Benefactor Schafter LWB		",
    "Benefactor Schafter LWB Armored		",
    "Benefactor Schafter V12		",
    "Benefactor Schafter V12 Armored		",
    "Benefactor Schwartzer		",
    "Benefactor Serrano		",
    "Benefactor Stirling GT		", ,
    "Benefactor Streiter		",
    "Benefactor Surano		",
    "Benefactor Terrorbyte		",
    "Benefactor Turreted Limo		",
    "Benefactor XLS		",
    "Benefactor XLS Armored		",
    "BF Bifta		",
    "BF Dune Buggy		",
    "BF Dune FAV		",
    "BF Injection		",
    "BF Ramp Buggy		",
    "BF Raptor		",
    "BF Space Docker		",
    "BF Surfer		",
    "Bollokan Prairie		",
    "Bravado	Banshee		",
    "Bravado	Banshee Topless		",
    "Bravado	Banshee 900R		",
    "Bravado	Bison		",
    "Bravado	Buffalo		",
    "Bravado	Buffalo S		",
    "Bravado	Duneloader		",
    "Bravado	FIB Buffalo		",
    "Bravado	Gauntlet		",
    "Bravado	Gresley		",
    "Bravado	HalfTrack		",
    "Bravado	Paradise		",
    "Bravado	Police Cruiser Buffalo		",
    "Bravado	RatLoader		",
    "Bravado	RatTruck		",
    "Bravado	Redwood Gauntlet		",
    "Bravado	Rumpo		",
    "Bravado	Rumpo Custom		",
    "Bravado	Sprunk Buffalo		", ,
    "Bravado	Verlierer		",
    "Bravado	Youga		",
    "Bravado	Youga Classic		",
    "Brute Airport Bus		",
    "Brute Ambulance		",
    "Brute Boxville		",
    "Brute Boxville Armored		",
    "Brute Bus		",
    "Brute Camper		",
    "Brute Dashound		",
    "Brute Police Riot		",
    "Brute Pony		",
    "Brute Rental Shuttle Bus	",
    "Brute Stockade		",
    "Brute Taco Van		",
    "Brute Tipper		",
    "Brute Tipper Classic		",
    "Brute Tour Bus		",
    "Brute Utility Truck		",
    "Brute Cherry Picker Utility Truck		",
    "Canis Bohdi		",
    "Canis Crusader		",
    "Canis Kalahari		",
    "Canis Kalahari Topless		",
    "Canis Kamacho		", ,
    "Canis Mesa		",
    "Canis Merryweather Mesa		",
    "Canis Seminole		",
    "Chariot Romero Hearse		",
    "Cheval Fugitive		",
    "Cheval Marshall		",
    "Cheval Picador		", ,
    "Cheval Surge		",
    "Cheval Taipan		",
    "Coil Brawler		",
    "Coil Cyclone		",
    "Coil Raiden		",
    "Coil Rocket Voltic		",
    "Coil Voltic		",
    "Coil Topless Voltic		",
    "Declasse Asea		",
    "Declasse Burger Shot Stallion		",
    "Declasse Burrito		",
    "Declasse Drift Tampa		",
    "Declasse FIB Granger		",
    "Declasse LMC Biker Burrito		", ,
    "Declasse Granger		",
    "Declasse Hotring Sabre		",
    "Declasse Lifegaurd Granger		",
    "Declasse Mamba		",
    "Declasse Moonbeam		",
    "Declasse Moonbeam Custom		",
    "Declasse Park Ranger Granger		",
    "Declasse Police Rancher		",
    "Declasse Police Transport Van		",
    "Declasse Premier		",
    "Declasse Rancher XL		",
    "Declasse Rhapsody		",
    "Declasse Sabre Turbo		",
    "Declasse Sabre Turbo Custom		",
    "Declasse Sheriff Granger		",
    "Declasse Stallion		",
    "Declasse Tampa		",
    "Declasse Tornado		",
    "Declasse Tornado Convertible		",
    "Declasse Tornado Custom		",
    "Declasse Tornado Rat Rod		",
    "Declasse Vigero		",
    "Declasse Voodoo		",
    "Declasse Voodoo Custom		",
    "Declasse Weaponized Tampa		",
    "Declasse Yosemite		",
    "Dewbauchee Exemplar		",
    "Dewbauchee JB 700		",
    "Dewbauchee Massacro		",
    "Dewbauchee Massacro RaceCar		",
    "Dewbauchee Rapid GT		",
    "Dewbauchee Rapid GT Classic		",
    "Dewbauchee Rapid GT Sports		",
    "Dewbauchee Seven - 70		",
    "Dewbauchee Specter		", ,
    "Dewbauchee Specter Custom		", ,
    "Dewbauchee Vagner		",
    "Dinka Akuma		",
    "Dinka Blista		",
    "Dinka Blista Compact		",
    "Dinka Double - T		",
    "Dinka Enduro		",
    "Dinka Go - Go Monkey Blista		",
    "Dinka Jester		", ,
    "Dinka Jester RaceCar		",
    "Dinka Jester Classic		",
    "Dinka Thrust		",
    "Dinka Vindicator		", ,
    "Dundreary Landstalker		",
    "Dundreary Regina		",
    "Dundreary Stretch		",
    "Dundreary Virgo Classic		",
    "Dundreary Virgo Classic Custom		",
    "Emperor	ETR1		",
    "Emperor	Habanero		",
    "Enus Cognoscenti		",
    "Enus Cognoscenti Armored		",
    "Enus Cognoscenti 55		",
    "Enus Cognoscenti 55 Armored",
    "Enus Cognoscenti Cabrio",
    "Enus Huntley S",
    "Enus Stafford",
    "Enus Super Diamond",
    "Enus Windsor",
    "Enus Windsor Drop",
    "Fathom	FQ 2",
    "Gallivanter Baller Classic",
    "Gallivanter Baller		",
    "Gallivanter Baller LE		",
    "Gallivanter Baller LE Armored		", , ,
    "Gallivanter Baller LE LWB		",
    "Gallivanter Baller LE LWB Armored		",
    "Grotti Bestia GTS		",
    "Grotti Brioso R / A		",
    "Grotti Carbonizzare		",
    "Grotti Cheetah		",
    "Grotti Cheetah Classic		",
    "Grotti GT500		",
    "Grotti Stinger		",
    "Grotti Topless Stinger		",
    "Grotti Stinger GT		",
    "Grotti Turismo Classic		",
    "Grotti Turismo R		",
    "Grotti Vigilante		",
    "Grotti Visione		",
    "Grotti X80 Proto		",
    "Hijak Khamelion		",
    "Hijak Ruston		",
    "HVY	Airtug		",
    "HVY	APC Tank		",
    "HVY	Barracks		", , ,
    "HVY	Barracks Semi		",
    "HVY	Biff		",
    "HVY	Chernobog		",
    "HVY	Crane		",
    "HVY	Cutter		",
    "HVY	Dock Handler		",
    "HVY	Docktug		",
    "HVY	Dozer		",
    "HVY	Dump		",
    "HVY	Forklift		",
    "HVY	Insurgent		",
    "HVY	Insurgent Pick - Up		",
    "HVY	Insurgent Pick - up Custom		",
    "HVY	Mixer Classic		",
    "HVY	Mixer		",
    "HVY	Nightshark		",
    "HVY	Ripley		",
    "HVY	Skylift		",
    "Imponte	Deluxo		",
    "Imponte	Duke O Death		",
    "Imponte	Dukes		",
    "Imponte	Nightshade		",
    "Imponte	Phoenix		",
    "Imponte	Ruiner		",
    "Imponte	Ruiner 2000		",
    "Invetero Coquette		",
    "Invetero Coquette Topless		",
    "Invetero Coquette BlackFin		",
    "Invetero Coquette Classic		",
    "Invetero Coquette Classic Topless		",
    "Jacksheepe Lawn Mower		",
    "JoBuilt	Hauler		", ,
    "JoBuilt	Hauler Custom		",
    "JoBuilt	Phantom		",
    "JoBuilt	Phantom Custom		",
    "JoBuilt	Phantom Wedge		",
    "JoBuilt	Rubble		",
    "JoBuilt	Trashmaster		",
    "Karin 190z		",
    "Karin Asterope		",
    "Karin BeeJay XL		",
    "Karin Dilettante		",
    "Karin Dilettante Patrol Vehicle		",
    "Karin Futo		",
    "Karin Intruder		",
    "Karin Kuruma		",
    "Karin Kuruma Armored		",
    "Karin Rebel		",
    "Karin Sultan		",
    "Karin Sultan RS		",
    "Karin Technical		",
    "Karin Technical Aqua		",
    "Karin Technical Custom		",
    "Lampadati Casco		",
    "Lampadati Felon		",
    "Lampadati Felon GT		",
    "Lampadati Furore GT		",
    "Lampadati Michelli GT		",
    "Lampadati Pigalle		",
    "Lampadati Tropos Rallye		",
    "Lampadati Viseris		",
    "LCC	Avarus		",
    "LCC	Hexer		",
    "LCC	Innovation		",
    "LCC	Sanctus		",
    "Maibatsu Manchez		",
    "Maibatsu Mule		",
    "Maibatsu Mule Armored		",
    "Maibatsu Mule Custom		",
    "Maibatsu Penumbra		",
    "Maibatsu Sanchez		",
    "Maibatsu Sanchez w / Livery		",
    "Mammoth	Patriot		",
    "Mammoth	Patriot Stretch		",
    "Mammoth	Thruster Jetpack		",
    "MTL	Brickade		",
    "MTL	Dune		",
    "MTL	Fire Truck		",
    "MTL	Flatbed		",
    "MTL	Packer		",
    "MTL	Pounder		",
    "MTL	Pounder Custom		",
    "MTL	Wastelander		",
    "Nagasaki BF400		",
    "Nagasaki Blazer		",
    "Nagasaki Blazer Aqua		",
    "Nagasaki Blazer Lifeguard		",
    "Nagasaki Caddy		",
    "Nagasaki Bunker Caddy		",
    "Nagasaki Caddy Utility		",
    "Nagasaki Carbon RS		",
    "Nagasaki Chimera		",
    "Nagasaki Hot Rod Blazer		",
    "Nagasaki Shotaro		",
    "Nagasaki Street Blazer		",
    "Obey 9F		",
    "Obey 9F Cabrio		",
    "Obey Omnis		",
    "Obey Rocoto		",
    "Obey Tailgater		",
    "Ocelot Ardent		",
    "Ocelet F620		",
    "Ocelet Jackal		",
    "Ocelet Lynx		",
    "Ocelet Pariah		",
    "Ocelet Penetrator		",
    "Ocelet Stromberg		",
    "Ocelet Swinger		",
    "Ocelet XA - 21		",
    "Overflod Autarch		",
    "  Overflod Entity XF		",
    "  Overflod Entity XXR		",
    "  Overflod Tyrant		",
    "  Pegassi Bati 801		",
    "  Pegassi Bati 801RR		",
    "  Pegassi Esskey		",
    "  Pegassi Faggio		",
    "  Pegassi Faggio Mod		",
    "  Pegassi FCR 1000		",
    "  Pegassi FCR 1000 Custom		",
    "  Pegassi Infernus		",
    "  Pegassi Infernus Classic		",
    "  Pegassi Monroe		",
    "  Pegassi Oppressor		",
    "  Pegassi Oppressor MK II		",
    "  Pegassi Osiris		",
    "  Pegassi Reaper		",
    "  Pegassi Ruffian		",
    "  Pegassi Tempesta		",
    "  Pegassi Tezeract		",
    "  Pegassi Torero		",
    "  Pegassi Vacca		",
    "  Pegassi Vortex		",
    "  Pegassi Zentorno		",
    "  Pfister 811		",
    "  Pfister Comet		",
    "  Pfister Comet Retro Custom		",
    "  Pfister Comet Safari		",
    "  Pfister Comet SR		",
    "  Pfister Neon		",
    "  Principe Diabolus		",
    "  Principe Diabolus Custom		",
    "  Principe Lectro		",
    "  Principe Nemesis		",
    "  Progen GP1		",
    "  Progen Itali GTB		",
    "  Progen Itali GTB Custom		",
    "  Progen T20		",
    "  Progen Tyrus		",
    "  RUNE Cheburek		",
    "  Schyster Fusilade		",
    "  Shitzu Defiler		",
    "  Shitzu Hakuchou		",
    "  Shitzu Hakuchou Drag Bike		",
    "  Shitzu PCJ 600		",
    "  Shitzu Vader		",
    "  Stanley	Fieldmaster		",
    "  Stanley	Tractor		",
    "  Truffade Adder		",
    "  Truffade Nero		",
    "  Truffade Nero Custom		",
    "  Truffade Z - Type		",
    "  Ubermacht Oracle		",
    "  Ubermacht Oracle XS		",
    "  Ubermacht Revolter		",
    "  Ubermacht SC1		",
    "  Ubermacht Sentinel		",
    "  Ubermacht Sentinel Classic		",
    "  Ubermacht Sentinel XS		",
    "  Ubermacht Zion		",
    "  Ubermacht Zion Cabrio		",
    "  Vapid Benson		",
    "  Vapid Blade		",
    "  Vapid Bobcat XL		",
    "  Vapid Bullet		",
    "  Vapid Caracara		",
    "  Vapid Chino		",
    "  Vapid Chino Custom		",
    "  Vapid Clown Van		",
    "  Vapid Contender		",
    "  Vapid Desert Raid		",
    "  Vapid Dominator		",
    "  Vapid Dominator GTX		",
    "  Vapid Ellie		",
    "  Vapid Flash GT		",
    "  Vapid FMJ		",
    "  Vapid GB200		",
    "  Vapid Guardian		",
    "  Vapid Hotknife		",
    "  Vapid Hustler		",
    "  Vapid Minivan		",
    "  Vapid Minivan Custom		",
    "  Vapid Peyote		",
    "  Vapid Pibwasser		",
    "  Vapid Police Cruiser		",
    "  Vapid Police Interceptor		",
    "  Vapid Police Prison Bus		",
    "  Vapid Radius		",
    "  Vapid Retinue		",
    "  Vapid Riata		",
    "  Vapid Sadler		",
    "  Vapid Sandking SWB		",
    "  Vapid Sandking XL		",
    "  Vapid Scrap Truck		",
    "  Vapid Sheriff Cruiser		",
    "  Vapid Slamvan		",
    "  Vapid Slamvan Custom		",
    "  Vapid Speedo		",
    "  Vapid Speedo Custom		",
    "  Vapid Stanier		",
    "  Vapid Taxi		",
    "  Vapid Liberator		",
    "  Vapid Tow Truck		",
    "  Vapid Large Tow Truck		",
    "  Vapid Trophy Truck		",
    "  Vapid Unmarked Cruiser		",
    "  Vapid Utility Truck		",
    "  Vulcar Fagaloa		",
    "  Vulcar Ingot		",
    "  Vulcar Warrener		",
    "  Weeny Issi		",
    "  Weeny Issi Classic		",
    "  Western Motorcycle Company	Bagger		",
    "  Western Motorcycle Company	Cliffhanger		",
    "  Western Motorcycle Company	Daemon		",
    "  Western Motorcycle Company	Daemon Custom	",
    "  Western Motorcycle Company	Gargoyle		",
    "  Western Motorcycle Company	Nightblade		",
    "  Western Motorcycle Company	Police Bike		",
    "  Western Motorcycle Company	Rat Bike		",
    "  Western Motorcycle Company	Sovereign		",
    "  Western Motorcycle Company	Wolfsbane		",
    "  Western Motorcycle Company	Zombie Bobber	",
    "  Western Motorcycle Company	Zombie Chopper	",
    "  Willard	Faction		",
    "  Willard	Faction Custom		",
    "  Willard	Faction Custom Donk		",
    "  Zirconium Journey",
    "  Zirconium Stratum"
]

async function Injection() {
    cars.forEach(car => {
        db.query("INSERT INTO `vehicles` (`cname`, `cadID`, `default_car`) VALUES ('" + car + "', '/', 'true')", (err, result) => {
            if (err) {
                return console.log(err)
            } else {
                console.log(`Added ${car}`)
            }
        })
    })
    db.end()
}

Injection()
